name: rss-feed-app-auto-deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  schedule:
    // # 3시간마다 배포
    - cron: "0 */3 * * *"

jobs:
  cron:
    runs-on: Windows
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI 
        run: yarn add vercel@latest

      - name: Build Project Artifacts 
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel 
        run: vercel deploy --prebuilt --prod  --token=${{ secrets.VERCEL_TOKEN }}